### ISSUE TITLE
Hi what about this warnings when run

### ISSUE THREAD

**Issue by icebergdelphi** [nordpos/nordpos#19]
Hi, and first of all thank you for the excellent project, i'd like to know why when y try to run the app always appears this errors:

feb 22, 2015 8:46:50 PM com.openbravo.pos.forms.AppConfig init
Información: Reading configuration file: C:\Users\Icebergdelphi\nordpos.properties
2015-02-22 20:46:51.083:INFO::AWT-EventQueue-0: Logging initialized @2495ms
2015-02-22 20:46:51.600:INFO:oejs.Server:Thread-2: jetty-9.2.5.v20141112
2015-02-22 20:46:51.774:INFO:oejs.ServerConnector:Thread-2: Started ServerConnector@459f2397{HTTP/1.1}{0.0.0.0:8135}
2015-02-22 20:46:51.775:INFO:oejs.Server:Thread-2: Started @3200ms
Sun Feb 22 20:46:52 CST 2015 : Apache Derby Network Server - 10.11.1.1 - (1616546) started and ready to accept connections on port 1527
Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
	at com.openbravo.pos.forms.JRootApp.initComponents(JRootApp.java:804)
	at com.openbravo.pos.forms.JRootApp.<init>(JRootApp.java:107)
	at com.openbravo.pos.forms.JRootFrame.initFrame(JRootFrame.java:53)
	at com.openbravo.pos.forms.StartPOS$1.run(StartPOS.java:148)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: java.util.MissingResourceException: Can't find bundle for base name pos_messages, locale en
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1499)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1322)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:721)
	at com.openbravo.beans.LocaleResources.addBundleName(LocaleResources.java:58)
	at com.openbravo.pos.forms.AppLocal.<clinit>(AppLocal.java:40)
	... 18 more

**Comment by svininykh** [comment]
Before run project in NetBeans, you need add resource folders:
```
./locales
./reports
./services
./templates
./transformations
```

**Comment by svininykh** [comment]
Project Properties -> Source Package Folders -> Add Folder...

![Source Package Folders](https://cloud.githubusercontent.com/assets/1005780/6334464/fe7b4684-bbbe-11e4-82f8-2265e0984979.png)

**Comment by icebergdelphi** [comment]
Thank you now Nord POS Rocks. :)
